### ISSUE TITLE
Fine-tune official crowdhuman_dla34.sh: error in modulated_deformable_im2col_cuda: invalid device function

### ISSUE THREAD

**Issue by quocnhat** [ifzhang/FairMOT#408]
Hi, thanks for your awesome work. I got this error when running sh experiments/crowdhuman_dla34.sh. How can I solve this? Any help is very appreciated.

error in modulated_deformable_im2col_cuda: invalid device function
Traceback (most recent call last):
  File "train.py", line 98, in <module>
    main(opt)
  File "train.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/cybercore/oldhome_2/nhat/workspace/project/cano/FairMOT/src/lib/trains/base_trainer.py", line 120, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/cybercore/oldhome_2/nhat/workspace/project/cano/FairMOT/src/lib/trains/base_trainer.py", line 72, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/home/cybercore/oldhome_2/quang/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cybercore/oldhome_2/nhat/workspace/project/cano/FairMOT/src/lib/trains/base_trainer.py", line 19, in forward
    outputs = self.model(batch['input'])
  File "/home/cybercore/oldhome_2/quang/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cybercore/oldhome_2/nhat/workspace/project/cano/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 473, in forward
    x = self.dla_up(x)
  File "/home/cybercore/oldhome_2/quang/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cybercore/oldhome_2/nhat/workspace/project/cano/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 411, in forward
    ida(layers, len(layers) -i - 2, len(layers))
  File "/home/cybercore/oldhome_2/quang/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cybercore/oldhome_2/nhat/workspace/project/cano/FairMOT/src/lib/models/networks/pose_dla_dcn.py", line 384, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/cybercore/oldhome_2/quang/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cybercore/oldhome_2/quang/anaconda3/envs/fairmot/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
Segmentation fault (core dumped)

**Comment by zengjie617789** [comment]
the problem is about cudnn installation error, not about FairMOT.

**Comment by quocnhat** [comment]
> the problem is about cudnn installation error, not about FairMOT.

You are right,  upgrade to Cuda 10.2 solved my problem
