### ISSUE TITLE
Why is CUDA_HOME None and Cuda not available when setup.py is compiled

### ISSUE THREAD

**Issue by DualMoonBird** [ifzhang/FairMOT#80]
D:\pyCharm\PycharmProjects\FairMOT\src\lib\models\networks\DCNv2>python setup.py build develop
信息: 用提供的模式无法找到文件。
torch.cuda.is_available:True,CUDA_HOME:None
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 41, in get_extensions
    raise NotImplementedError('Cuda is not available')
NotImplementedError: Cuda is not available

**Comment by StianHanssen** [comment]
I was annoyed with this as well. It seems Cuda Toolkit from the pytorch binaries is a subset of Cuda Toolkit and does not contain nvcc among other things. I tried installing a local version of Cuda Toolkit, but that interefered with the conda version so I got False when calling `torch.cuda.is_available()`.

**Comment by DualMoonBird** [comment]
> I was annoyed with this as well. It seems Cuda Toolkit from the pytorch binaries is a subset of Cuda Toolkit and does not contain nvcc among other things. I tried installing a local version of Cuda Toolkit, but that interfered with the conda version so I got False when calling torch.cuda.is_available().
> Then I found out they had a docker file in /build.
> I set it up with:
> docker build -t fair-mot --build-arg nvidia/cuda ./build
> Then to enter the NVIDIA docker environment run:
> docker run --rm --gpus all -v $(pwd)/:/FairMOT -ti fair-mot /bin/bash
> In this case my ${FAIRMOT_ROOT} is called FairMOT, I assume yours will be the same if you just clone the repo.
> Then I believe you should be able to run most commands normally like the README says. The conda environment they created in the docker build is called: py36.
> In case you don't have nvidia docker and you are on ubutntu:
> 
> Check requirements: https://github.com/anibali/docker-pytorch#cuda-requirements
> Follow this: https://github.com/NVIDIA/nvidia-docker#ubuntu-16041804-debian-jessiestretchbuster
> Run: sudo apt-get install nvidia-docker2
> Run: sudo systemctl daemon-reload



> I was annoyed with this as well. It seems Cuda Toolkit from the pytorch binaries is a subset of Cuda Toolkit and does not contain nvcc among other things. I tried installing a local version of Cuda Toolkit, but that interfered with the conda version so I got False when calling torch.cuda.is_available().
> Then I found out they had a docker file in /build.
> I set it up with:
> docker build -t fair-mot --build-arg nvidia/cuda ./build
> Then to enter the NVIDIA docker environment run:
> docker run --rm --gpus all -v $(pwd)/:/FairMOT -ti fair-mot /bin/bash
> In this case my ${FAIRMOT_ROOT} is called FairMOT, I assume yours will be the same if you just clone the repo.
> Then I believe you should be able to run most commands normally like the README says. The conda environment they created in the docker build is called: py36.
> In case you don't have nvidia docker and you are on ubutntu:
> 
> Check requirements: https://github.com/anibali/docker-pytorch#cuda-requirements
> Follow this: https://github.com/NVIDIA/nvidia-docker#ubuntu-16041804-debian-jessiestretchbuster
> Run: sudo apt-get install nvidia-docker2
> Run: sudo systemctl daemon-reload




> I was annoyed with this as well. It seems Cuda Toolkit from the pytorch binaries is a subset of Cuda Toolkit and does not contain nvcc among other things. I tried installing a local version of Cuda Toolkit, but that interfered with the conda version so I got False when calling torch.cuda.is_available().
> Then I found out they had a docker file in /build.
> I set it up with:
> docker build -t fair-mot --build-arg nvidia/cuda ./build
> Then to enter the NVIDIA docker environment run:
> docker run --rm --gpus all -v $(pwd)/:/FairMOT -ti fair-mot /bin/bash
> In this case my ${FAIRMOT_ROOT} is called FairMOT, I assume yours will be the same if you just clone the repo.
> Then I believe you should be able to run most commands normally like the README says. The conda environment they created in the docker build is called: py36.
> In case you don't have nvidia docker and you are on ubutntu:
> 
> Check requirements: https://github.com/anibali/docker-pytorch#cuda-requirements
> Follow this: https://github.com/NVIDIA/nvidia-docker#ubuntu-16041804-debian-jessiestretchbuster
> Run: sudo apt-get install nvidia-docker2
> Run: sudo systemctl daemon-reload

The two dockerfiles one is provided by you another is in FairMOT project. So which should I use？

**Comment by DualMoonBird** [comment]
The two dockerfiles one is provided by you another is in FairMOT project. So which should I use？

**Comment by StianHanssen** [comment]
Use the one provided by FairMOT as my updated comment says :)

**Comment by StianHanssen** [comment]
Sorry for the wait! I found a solution! Please discard everything I said about docker. I managed to install Cuda Tool Kit locally in such a way that we get nvcc and `torch.cuda.is_available()` is True. I tested it and everything seem to be running fine.

I followed a tutorial I found for CUDA 9 and modified it to CUDA 10. I made a gist here:
https://gist.github.com/StianHanssen/3486986115e5fe5edc89c17f1adbdc61

Before installing make sure there isn't a locally installed version of Cuda Tool Kit on your machine. Once you have installed a local version of Cuda Tool Kit you should be able to follow the instructions in the README as normal.

**Comment by DualMoonBird** [comment]
Thanks a lot,I have run it on my cloud host,the localhost configuration is so bad that I gave up running it locally :)

**Comment by JayLIU0911** [comment]
Hi, I am struggling with configuring the correct docker environment to run on cloud. If you have succeeded on this, could you please share with me the Dockerfile you used? I would really appreciate that!
